server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/springboot_demo
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}

#    url: jdbc:mysql://sh-cynosdbmysql-grp-mudxdw6u.sql.tencentcdb.com:25560/springboot_demo
#    username: root
#    password: 852456kid!
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml


tcp:
  port: 8081
  heartbeatTimeout: 1000
udp:
  port: 8082